### ISSUE TITLE
issue updating 0.0.12 to 0.0.14

### ISSUE THREAD

**Issue by eatm1** [btubbs/sseclient#1]
Had my project running with 0.0.12, and as I installed again it got bumped up to 0.0.14 and I started getting this error:

```
File "xxxx/lib/python2.7/site-packages/sseclient.py", line 64, in __next__
    nextline = self.resp_file.readline()
AttributeError: 'SSEClient' object has no attribute 'resp_file'
```

It seems to be an issue with the request not having `raw` or something, as thecode has the line 
`self.resp_file = self.resp.raw`

requirement is for `requests>2.0.0` and I'm using 2.11.1

should the request requirement be higher?

For now, I downgraded to 0.0.12, but looking for a solution to this issue.
Thanks

**Comment by xqt** [comment]
I guess this is solved within 6820dc808fc669ee55baf8261120820020036050 as part of 0.0.16
