### ISSUE TITLE
How to pass timeout seconds.

### ISSUE THREAD

**Issue by samta93** [btubbs/sseclient#18]
There are cases when a client would not know if the connection is still healthy. I encountered similar issue when server closed the connection but client is still listening. In such cases I would want to close the connection (after timeout) and reopen. 
Basically I should be able to do something like:
$ self.resp = requester.get(self.url, timeout=120, stream=True, **self.requests_kwargs)
But the library doesnt allow me the way to pass timeout value.

**Comment by btubbs** [comment]
This should be already handled.  Any extra keyword arguments you pass when instantiating your SSEClient object are passed along to the underlying Requests library (as shown in your example above).  So you should just need to pass that timeout argument when creating your client object.  Example:

```
client = SSEClient(url, timeout=1234)
```

Note that the underlying Requests library specifies _two_ kinds of timeouts: a connect timeout and a read timeout.  If you pass just one number as the timeout, that duration will be used for both.  You can have different connect vs read timeouts by passing a tuple of two numbers instead.  See http://docs.python-requests.org/en/master/user/advanced/#timeouts.
