### ISSUE TITLE
Please provide a version string with your package

### ISSUE THREAD

**Issue by xqt** [btubbs/sseclient#19]
Please provide a `__version__` string with your package. This is needed to verify the right version at runtime.

**Comment by btubbs** [comment]
Good idea.  Can you send a pull request?

**Comment by xqt** [comment]
Enclosed you'l find the patch file.
Sorry I am not familiar how to upload pull requests to github projects yet.

[version.zip](https://github.com/btubbs/sseclient/files/2898281/version.zip)

**Comment by xqt** [comment]
See my pull request now

**Comment by btubbs** [comment]
Thank you!
