### ISSUE TITLE
sseclient 0.0.23 fails with AttributeError

### ISSUE THREAD

**Issue by xqt** [btubbs/sseclient#22]
sseclient 0.0.23 fails with AttributeError: '_fileobject' object has no attribute 'read1'
See https://phabricator.wikimedia.org/T219024

**Comment by mutantmonkey** [comment]
Since Python 3.5, `http.client.HTTPResponse`  implements `io.BufferedIOBase`, which includes `read1`. Python 3.4 and prior versions do not have it available, so this is probably why this is failing in your test environment.
