### ISSUE TITLE
sseclient can't detect end of next event?

### ISSUE THREAD

**Issue by docelic** [btubbs/sseclient#27]
I am connecting to a server and not receiving any server-sent events.

After looking into the code, this is because in sseclient.py function __next__(), the code beginning with `while not self._event_complete()` never completes, so it doesn't complete and process any events, but it only appends to the internal buffer.

Any hints why this might be happening? Thanks.

**Comment by docelic** [comment]
Can the issue be in:

```
self.buf += decoder.decode(next_chunk)
```

End of field is searched using a regex `r'\r\n\r\n|\r\r|\n\n'`, which leads me to believe that the content of `self.buf` should be string.

However, if I print `self.buf`, the content is all binary.

**Comment by docelic** [comment]
Found the root cause - the server's response is gzip-encoded and this is reaching the SSE client in raw form.

**Comment by GPistre** [comment]
So, what was your solution ?

**Comment by docelic** [comment]
@GPistre one way is to decode gzip stream yourself.
However the solution I took was to send `'Accept-Encoding': 'identity'` in the request headers to make sure that the server will respond with uncompressed data.

**Comment by TheSandDoctor** [comment]
Just for the record this was outright fixed with PR #37 .
