### ISSUE TITLE
Spurious replacement characters (U+FFFD) in events

### ISSUE THREAD

**Issue by Count-Count** [btubbs/sseclient#38]
The unicode decoder state is not saved across SSEClient.__next__() calls. Thus if the buffer ends in the middle of a multi-byte encoding the decoder fails to decode the char on the next call.

**Comment by TheSandDoctor** [comment]
Thanks so much for fixing @btubbs ! :)

**Comment by dvorapa** [comment]
Per https://phabricator.wikimedia.org/T181443 the issue seems to be still there :/

**Comment by TheSandDoctor** [comment]
Can confirm. Experienced post-merge @btubbs @Count-Count . Probably want to re-open the issue.
