### ISSUE TITLE
The first event retrieved by sseclient is always empty

### ISSUE THREAD

**Issue by xqt** [btubbs/sseclient#41]
`
.>>> from sseclient import SSEClient
.>>> client = SSEClient(url='https://stream.wikimedia.org/v2/stream/recentchange')
.>>> data = next(client)
.>>> data.__dict__
{'data': '', 'event': 'message', 'id': None, 'retry': None}
.>>> data = next(client)
.>>> data.__dict__
{'data': '{"$schema":"/mediawiki/recentchange/1.0.0","meta":{"uri":"https://commons.wikimedia.org/wiki/File:Geschichte_des_Schultei%C3%9Fenamts_und_der_Stadt_Neumarkt_014.jpg","request_id":"Xj6I2ApAED4AADHcxFEAAABL","id":"7573678b-87b2-4325-81f8-e338613e537b","dt":"2020-02-08T10:09:30Z","domain":"commons.wikimedia.org","stream":"mediawiki.recentchange","topic":"eqiad.mediawiki.recentchange","partition":0,"offset":2157854683},"id":1327149461,"type":"log","namespace":6,"title":"File:Geschichte des Schulteißenamts und der Stadt Neumarkt 014.jpg","comment":"User created page with UploadWizard","timestamp":1581156570,"user":"DALIBRI","bot":false,"log_id":290782528,"log_type":"upload","log_action":"upload","log_params":{"img_sha1":"5oe8esm1e76smmt6zbv811c0m7ay1jo","img_timestamp":"20200208100930"},"log_action_comment":"uploaded &quot;[[File:Geschichte des Schulteißenamts und der Stadt Neumarkt 014.jpg]]&quot;: User created page with UploadWizard","server_url":"https://commons.wikimedia.org","server_name":"commons.wikimedia.org","server_script_path":"/w","wiki":"commonswiki","parsedcomment":"User created page with UploadWizard"}', 'event': 'message', 'id': '[{"topic":"eqiad.mediawiki.recentchange","partition":0,"timestamp":1581156570001},{"topic":"codfw.mediawiki.recentchange","partition":0,"offset":-1}]', 'retry': None}
>>> 
`

**Comment by TheSandDoctor** [comment]
This has actually led to [a patch](https://phabricator.wikimedia.org/T244491) for Pywikibot to not display the first message. Having it fixed at the source would indeed be ideal.

**Comment by Shoelace** [comment]
the root cause of this the that wikimedia stream starts with a single "comment event"
of

    :OK

SSEClient correctly ignores the comment line.. but still emits a "empty" event , which is against the spec.
i have a fix.. will upload a PR shortly

**Comment by Shoelace** [comment]
a python 3 complient test is

    from sseclient import SSEClient
    client = SSEClient('https://stream.wikimedia.org/v2/stream/recentchange')
    data = next(client)
    print(data.__dict__)
    data = next(client)
    print(data.__dict__)
