### ISSUE TITLE
Default chunk size of 1024 is inappropriate (regression in 0.0.16)

### ISSUE THREAD

**Issue by mutantmonkey** [btubbs/sseclient#8]
With the changes made in 6820dc808fc669ee55baf8261120820020036050, event handling has severely regressed. Instead of messages being processed as they come in, they are buffered until the chunk size is hit and then processed. For my use case, I need messages to be processed immediately, and I believe this would be the expected behavior for most other use cases of this library.

I've found that setting the chunk size to 1 fixes this issue, and I believe that to be the only acceptable chunk size for this library; buffering messages until the chunk size is simply not appropriate in a protocol where one or two characters are the difference between a message being processed or buffered. For example, assume that I have events that happen to be exactly 1024 bytes long, not including the message separator; until the next message arrives and fills up the buffer containing the `\r\n`, the first message will not be processed.

Another potential solution is to continue to use a large chunk size to avoid high CPU load on noisy endpoints, but with a short timeout on the read so that quieter SSE endpoints do not suffer from this issue.

I'm not sure if you want to back out the changes made in that commit or simply change the default chunk size, but please let me know if I can be of any assistance in getting this resolved.

**Comment by btubbs** [comment]
These are good points.  I would like the library to provide good performance out of the box both for streams where there are occasional small messages and streams where messages come in like a firehose (which I think was the case for @ottomata when he made the chunk size change).

I'd rather change defaults than back out changes.  The chunk size wasn't configurable before that commit.

I just read over the [Requests docs on timeouts](http://docs.python-requests.org/en/master/user/advanced/#timeouts).  It looks like a custom timeout can currently be passed in to SSEClient as part of the kwargs that get passed through to Requests.  I'm not opposed to setting a default that's better tuned to our use case.  Do you know what the current default values are in Requests for the connection timeout and send timeout?

**Comment by mutantmonkey** [comment]
Thanks for looking into this so quickly. It seems like requests uses the timeout functionality from urllib3, which uses the default Python socket timeout. As far as I can tell, there is no default Python socket timeout and the actual timeout depends on the socket connection timeout on the underlying platform.

I did a bit of digging in Requests and found that [it also accepts a chunk size of None](http://docs.python-requests.org/en/master/api/#requests.Response.iter_content), which seems like it might be exactly what we want:
> chunk_size must be of type int or None. A value of None will function differently depending on the value of stream. stream=True will read data as it arrives in whatever size the chunks are received. If stream=False, data is returned as a single chunk.

I've made this change to one of my clients to see if this works as expected; I'll post here with an update soon. The streams I'm working with aren't very busy, so it would be good to hear from someone who has a busier stream on what, if any, performance impact this will have versus a larger chunk size.

**Comment by btubbs** [comment]
If we're going to set a default value for (connection_timeout, send_timeout) as a kwarg in __init__, what values do you think make sense?

**Comment by mutantmonkey** [comment]
I think it's going to require a bit more than adjusting the timeouts to fix the problem; I've tested a timeout of one second as a read timeout, and what happens is that the process will wake up after the read times out, wasting CPU cycles. I also ran into an issue during testing with a high latency connection where the read timeout ended up bubbling up after several failures, even though it wouldn't normally have done so.

Ultimately, I think that urllib3's handling of chunked streams is just too primitive for high performance use cases. If you're set on using timed reads as a solution, a call to `select` will at least work around the busy-wait issue mentioned above, but it doesn't fix everything. Really, why stop at a chunk size of 1024? A larger chunk size is always going to provide better performance provided that you have the memory for it.

**Comment by mutantmonkey** [comment]
My initial suggestion of using a timed read was flawed, unfortunately; took me a while to remember some of my systems programming. This will end up giving us a busy-wait situation because the process is going to wake up each time the read times out.

It seems that urllib3's handling of chunked streams is simply not designed to handle this type of use case; in fact, it seems actively hostile to it. For instance, setting chunk_size to None as mentioned earlier causes it to ignore the last 2 bytes of whatever it has determined to be the appropriate length to read:
```python
        if amt is None:
            chunk = self._fp._safe_read(self.chunk_left)
            returned_chunk = chunk
            self._fp._safe_read(2)  # Toss the CRLF at the end of the chunk.
            self.chunk_left = None
```

Ultimately, the problem seems to be that for whatever reason, either urllib3, http.client, or both do not support short reads properly unless it hits EOF when reading; using a chunk size of 1024 should really not cause a problem like this. It's going to take some more digging to figure out why, but `recv` and `recvfrom` are supposed to do short reads and not block unless you have the `MSG_WAITALL` flag set.

**Comment by OlafvdSpek** [comment]
Any progress?

**Comment by mutantmonkey** [comment]
Almost two years later, I did finally spend some time tracking this down. Unfortunately, in order to fix this, you have to go deep into requests, urllib3, and http.client and pull out the underlying `io.BufferedReader` object that represents the response from the server. That object has a `read1` method that will return only the buffered bytes and eliminate this blocking behavior: https://docs.python.org/3/library/io.html#io.BufferedReader.read1

In my testing, I ended up getting the intended behavior by putting my own custom `iter_content` method together, but it's far from production-ready:
````python
    def iter_content(self):
        def generate():
            while True:
                if hasattr(self.resp.raw, '_fp'):
                    yield self.resp.raw._fp.fp.read1(self.chunk_size)
                else:
                    # _fp is not available, this means that we cannot use short
                    # reads and this will block until the full chunk size is
                    # actually read
                    yield self.resp.raw.read(self.chunk_size)

        return generate()
```

You'd ideally want to remove that `hasattr` call, but doing so will break the tests because it doesn't fully mock `urllib3.HTTPResponse`.

**Comment by btubbs** [comment]
Cool!  What's missing to make it production ready?

**Comment by waelAbass** [comment]
please, It is not clear for me how the problem of default 1024 is handled.
