### ISSUE TITLE
0.0.18 lags

### ISSUE THREAD

**Issue by doczoidberg** [btubbs/sseclient#9]
I updated my package from 0.0.12 to 0.0.18 and have lags up to 1minute.

I use it with firebase and have no lags with 0.0.12. Not sure why

**Comment by doczoidberg** [comment]
seems that the problems appears since 0.0.17

**Comment by btubbs** [comment]
This may be related to the chunk_size changes from https://github.com/btubbs/sseclient/commit/ed605a0e4e3cd120de335066ed9fe382e1329e2e.  Is it fixed if you pass chunk_size=1 when initializing the SSEClient object?

**Comment by OlafvdSpek** [comment]
It does improve behavior but with the following code I'm still not receiving the initial event right away, the event seems to stuck until some more events are send.

```
from sseclient import SSEClient # pip install sseclient

url = 'https://x.firebaseio.com'
messages = SSEClient(url + '/.json', chunk_size = 1)
for msg0 in messages :
  print(msg0.data)
```

**Comment by doczoidberg** [comment]
just uninstall with pip and use pip to install an older version

**Comment by OlafvdSpek** [comment]
@btubbs With chunk_size=1 big events (say 1MB) take ages and tons of CPU.
